---
  - name: Add docker repository key
    apt_key:
      keyserver: hkp://pgp.mit.edu:80
      id: 58118E89F3A912897C070ADBF76221572C52609D

  - name: Add docker repository
    apt_repository:
      repo: deb https://apt.dockerproject.org/repo debian-jessie main > /etc/apt/sources.list.d/docker.list
      filename: docker

  - name: get docker compose
    get_url:
      url: https://github.com/docker/compose/releases/download/1.5.2/docker-compose-Linux-x86_64
      dest: /usr/local/bin/docker-compose
      mode: 0755   

  - name: Install docker-engine package
    apt:
      name: docker-engine

  - name: Add koffi_t user to docker group
    user:
      name: koffi_t
      groups: docker
      append: yes
