pipeline {
    agent any

    stages {
        stage('Install npm dependencies') {
            sh "npm install"
        }

        stage('Run functionel tests') {
            sh "npm run test:cucumber"
        }

        stage('Run unit tests') {
            sh "npm run test:unit"
        }
    }
}