Vagrant.require_version ">= 1.5"

Vagrant.configure("2") do |config|

    config.vm.provider :virtualbox do |v|
        v.gui = false
        v.name = "etna.devops.vm2"
        v.customize [
            "modifyvm", :id,
            "--name", "etna.devops.vm2",
            "--memory", 1024,
            "--natdnshostresolver1", "on",
            "--cpus", 1,
        ]
    end

    config.vm.box = "ubuntu/trusty32"

    config.vm.box_url = "https://vagrantcloud.com/ubuntu/boxes/trusty32/versions/14.04/providers/virtualbox.box"

    config.vm.network :private_network, ip: "192.168.33.102"
    config.ssh.forward_agent = true

    config.vm.synced_folder ".", "/vagrant", create: true
end
